-- Register the crawler sites that already exist in scripts/crawler/src/sites.js
-- so the collection source dashboard can monitor and run them individually.

UPDATE collection_sources
SET
  source_slug = 'mfac',
  name = '마포문화재단',
  list_url = 'https://www.mfac.or.kr/communication/notice_all_list.jsp',
  config_json = jsonb_build_object(
    'site_ids', jsonb_build_array('mfac'),
    'adapter', 'mfac',
    'maxPages', 2,
    'boards', jsonb_build_array(
      jsonb_build_object('name', '재단소식', 'url', 'https://www.mfac.or.kr/communication/notice_all_list.jsp', 'category', '문화')
    )
  ),
  updated_at = now()
WHERE source_slug = 'mapo-culture-foundation'
  AND NOT EXISTS (
    SELECT 1 FROM collection_sources WHERE source_slug = 'mfac'
  );

INSERT INTO collection_sources (
  source_slug,
  name,
  source_type,
  region_scope,
  region_name,
  homepage_url,
  list_url,
  collection_method,
  collection_interval_minutes,
  priority,
  status,
  reliability,
  monthly_expected_posts,
  config_json,
  notes
) VALUES
  (
    'seoul-city',
    '서울특별시',
    'local_government',
    'sido',
    '서울특별시',
    'https://www.seoul.go.kr',
    'https://www.seoul.go.kr/news/news_notice.do',
    'html',
    720,
    80,
    'active',
    'medium',
    12,
    '{"site_ids":["seoul-city"],"adapter":"seoul-city","maxPages":2,"boards":[{"name":"공고/고시","url":"https://www.seoul.go.kr/news/news_notice.do","category":"공고"}]}'::jsonb,
    '서울시 공고/고시 기존 크롤러 설정 연동'
  ),
  (
    'mapo-gu',
    '마포구청',
    'local_government',
    'sigungu',
    '서울특별시 마포구',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/main/board/notice/list',
    'html',
    720,
    82,
    'active',
    'medium',
    20,
    '{"site_ids":["mapo-gu"],"adapter":"mapo-gu","maxPages":2,"boards":[{"name":"공지사항","url":"https://www.mapo.go.kr/site/main/board/notice/list","category":"공지"},{"name":"채용공고","url":"https://www.mapo.go.kr/site/main/board/recruit/list","category":"채용"}]}'::jsonb,
    '마포구청 공지/채용 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-gongdeok',
    '마포구 공덕동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 공덕동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/gongdeok/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-gongdeok"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/gongdeok/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 공덕동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-ahyeon',
    '마포구 아현동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 아현동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/ahyeon/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-ahyeon"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/ahyeon/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 아현동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-dohwa',
    '마포구 도화동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 도화동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/dohwa/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-dohwa"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/dohwa/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 도화동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-yonggang',
    '마포구 용강동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 용강동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/yonggang/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-yonggang"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/yonggang/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 용강동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-daeheung',
    '마포구 대흥동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 대흥동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/daeheung/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-daeheung"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/daeheung/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 대흥동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-yeomni',
    '마포구 염리동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 염리동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/yeomni/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-yeomni"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/yeomni/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 염리동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-sinsu',
    '마포구 신수동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 신수동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/sinsu/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-sinsu"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/sinsu/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 신수동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-seogang',
    '마포구 서강동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 서강동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/seogang/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-seogang"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/seogang/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 서강동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-seogyo',
    '마포구 서교동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 서교동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/seogyo/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-seogyo"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/seogyo/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 서교동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-hapjeong',
    '마포구 합정동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 합정동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/hapjeong/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-hapjeong"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/hapjeong/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 합정동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-mangwon1',
    '마포구 망원1동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 망원1동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/mangwon1/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-mangwon1"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/mangwon1/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 망원1동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-mangwon2',
    '마포구 망원2동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 망원2동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/mangwon2/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-mangwon2"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/mangwon2/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 망원2동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-yeonnam',
    '마포구 연남동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 연남동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/yeonnam/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-yeonnam"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/yeonnam/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 연남동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-seongsan1',
    '마포구 성산1동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 성산1동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/seongsan1/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-seongsan1"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/seongsan1/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 성산1동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-seongsan2',
    '마포구 성산2동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 성산2동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/seongsan2/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-seongsan2"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/seongsan2/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 성산2동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-dong-sangam',
    '마포구 상암동 주민센터',
    'local_government',
    'dong',
    '서울특별시 마포구 상암동',
    'https://www.mapo.go.kr',
    'https://www.mapo.go.kr/site/sangam/board/notice/list',
    'html',
    720,
    62,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-dong-sangam"],"adapter":"mapo-dong","maxPages":2,"boards":[{"name":"주민센터 소식","url":"https://www.mapo.go.kr/site/sangam/board/notice/list","category":"동주민센터"}]}'::jsonb,
    '마포구 상암동 주민센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-council',
    '마포구의회',
    'local_government',
    'sigungu',
    '서울특별시 마포구',
    'https://council.mapo.seoul.kr',
    'https://council.mapo.seoul.kr/kr/news/bbsNotice.do',
    'html',
    720,
    70,
    'active',
    'medium',
    12,
    '{"site_ids":["mapo-council"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"https://council.mapo.seoul.kr/kr/news/bbsNotice.do","category":"공지"},{"name":"입법예고","url":"https://council.mapo.seoul.kr/kr/news/bbsLaw.do","category":"입법"}]}'::jsonb,
    '마포구의회 기존 크롤러 설정 연동'
  ),
  (
    'mfmc',
    '마포구시설관리공단',
    'sports',
    'sigungu',
    '서울특별시 마포구',
    'https://www.mfmc.or.kr',
    'https://www.mfmc.or.kr/view/bbs/board.php?tbname=notice',
    'html',
    720,
    70,
    'active',
    'medium',
    12,
    '{"site_ids":["mfmc"],"adapter":"mfmc","maxPages":2,"boards":[{"name":"공지사항","url":"https://www.mfmc.or.kr/view/bbs/board.php?tbname=notice","category":"공지"},{"name":"채용공고","url":"https://www.mfmc.or.kr/view/bbs/board.php?tbname=recruit","category":"채용"}]}'::jsonb,
    '마포구시설관리공단 기존 크롤러 설정 연동'
  ),
  (
    'mfac',
    '마포문화재단',
    'culture',
    'sigungu',
    '서울특별시 마포구',
    'https://www.mfac.or.kr',
    'https://www.mfac.or.kr/communication/notice_all_list.jsp',
    'html',
    720,
    78,
    'active',
    'medium',
    12,
    '{"site_ids":["mfac"],"adapter":"mfac","maxPages":2,"boards":[{"name":"재단소식","url":"https://www.mfac.or.kr/communication/notice_all_list.jsp","category":"문화"}]}'::jsonb,
    '마포문화재단 기존 크롤러 설정 연동'
  ),
  (
    'mapo-scholarship',
    '마포인재육성장학재단',
    'foundation',
    'sigungu',
    '서울특별시 마포구',
    'http://www.mapojh.or.kr',
    'http://www.mapojh.or.kr/notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-scholarship"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"http://www.mapojh.or.kr/notice","category":"장학"}]}'::jsonb,
    '마포인재육성장학재단 기존 크롤러 설정 연동'
  ),
  (
    'mapo-culture',
    '마포문화원',
    'culture',
    'sigungu',
    '서울특별시 마포구',
    'http://www.mapocc.or.kr',
    'http://www.mapocc.or.kr/board/notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-culture"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"http://www.mapocc.or.kr/board/notice","category":"문화"}]}'::jsonb,
    '마포문화원 기존 크롤러 설정 연동'
  ),
  (
    'mapo-employ',
    '마포구고용복지지원센터',
    'welfare',
    'sigungu',
    '서울특별시 마포구',
    'https://mapoworkfare.or.kr',
    'https://mapoworkfare.or.kr/notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-employ"],"adapter":"mapo-employ","maxPages":2,"boards":[{"name":"공지사항","url":"https://mapoworkfare.or.kr/notice","category":"일자리"}]}'::jsonb,
    '마포구고용복지지원센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-labor',
    '마포구노동자종합지원센터',
    'welfare',
    'sigungu',
    '서울특별시 마포구',
    'https://mapolabor.org',
    'https://mapolabor.org/community/news',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-labor"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"https://mapolabor.org/community/news","category":"노동"}]}'::jsonb,
    '마포구노동자종합지원센터 기존 크롤러 설정 연동'
  ),
  (
    'mangwon-youth',
    '구립망원청소년문화센터',
    'youth_center',
    'sigungu',
    '서울특별시 마포구',
    'http://www.mwyouth.org',
    'http://www.mwyouth.org/bbs/board.php?bo_table=notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mangwon-youth"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"http://www.mwyouth.org/bbs/board.php?bo_table=notice","category":"청소년"}]}'::jsonb,
    '구립망원청소년문화센터 기존 크롤러 설정 연동'
  ),
  (
    'dohwa-youth',
    '구립도화청소년문화의집',
    'youth_center',
    'sigungu',
    '서울특별시 마포구',
    'http://www.dhyouth.or.kr',
    'http://www.dhyouth.or.kr/new2024/board/notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["dohwa-youth"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"http://www.dhyouth.or.kr/new2024/board/notice","category":"청소년"}]}'::jsonb,
    '구립도화청소년문화의집 기존 크롤러 설정 연동'
  ),
  (
    'mapo-youth',
    '구립마포청소년문화의집',
    'youth_center',
    'sigungu',
    '서울특별시 마포구',
    'https://www.mycc.or.kr',
    'https://www.mycc.or.kr/p_community/sub01.php',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-youth"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"https://www.mycc.or.kr/p_community/sub01.php","category":"청소년"}]}'::jsonb,
    '구립마포청소년문화의집 기존 크롤러 설정 연동'
  ),
  (
    'mapo-disabled',
    '마포장애인종합복지관',
    'welfare',
    'sigungu',
    '서울특별시 마포구',
    'https://mapowelfare.or.kr',
    'https://mapowelfare.or.kr/bbs/board.php?bo_table=notice',
    'html',
    720,
    70,
    'active',
    'medium',
    12,
    '{"site_ids":["mapo-disabled"],"adapter":"mapo-welfare","maxPages":2,"boards":[{"name":"공지사항","url":"https://mapowelfare.or.kr/bbs/board.php?bo_table=notice","category":"복지"},{"name":"채용공고","url":"https://mapowelfare.or.kr/bbs/board.php?bo_table=recruit","category":"채용"}]}'::jsonb,
    '마포장애인종합복지관 기존 크롤러 설정 연동'
  ),
  (
    'mapo-senior',
    '마포노인복지센터',
    'welfare',
    'sigungu',
    '서울특별시 마포구',
    'https://mapocare.or.kr',
    'https://mapocare.or.kr/bbs/board.php?bo_table=notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-senior"],"adapter":"generic-board","maxPages":2,"boards":[{"name":"공지사항","url":"https://mapocare.or.kr/bbs/board.php?bo_table=notice","category":"노인복지"}]}'::jsonb,
    '마포노인복지센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-sports',
    '마포구민체육센터',
    'sports',
    'sigungu',
    '서울특별시 마포구',
    'https://yeyak.maposc.or.kr',
    'https://yeyak.maposc.or.kr/news/board/llist/notice',
    'html',
    720,
    70,
    'active',
    'medium',
    6,
    '{"site_ids":["mapo-sports"],"adapter":"maposc-yeyak","maxPages":2,"boards":[{"name":"공지사항","url":"https://yeyak.maposc.or.kr/news/board/llist/notice","category":"체육"}]}'::jsonb,
    '마포구민체육센터 기존 크롤러 설정 연동'
  ),
  (
    'kesco',
    '한국전기안전공사',
    'other',
    'national',
    '전국',
    'https://www.kesco.or.kr',
    'https://www.kesco.or.kr/sfcont/selectPageListSfCont.do',
    'html',
    1440,
    55,
    'active',
    'medium',
    4,
    '{"site_ids":["kesco"],"adapter":"kesco","maxPages":2,"boards":[{"name":"공지사항","url":"https://www.kesco.or.kr/sfcont/selectPageListSfCont.do","category":"안전"}]}'::jsonb,
    '한국전기안전공사 기존 크롤러 설정 연동'
  ),
  (
    'mapo-kids-meal',
    '마포구어린이급식관리지원센터',
    'welfare',
    'sigungu',
    '서울특별시 마포구',
    'https://ccfsm.foodnara.go.kr',
    'https://ccfsm.foodnara.go.kr/mapo/',
    'html',
    720,
    60,
    'active',
    'medium',
    4,
    '{"site_ids":["mapo-kids-meal"],"adapter":"ccfsm","maxPages":2,"boards":[{"name":"공지사항","url":"https://ccfsm.foodnara.go.kr/mapo/","category":"급식"}]}'::jsonb,
    '마포구어린이급식관리지원센터 기존 크롤러 설정 연동'
  ),
  (
    'mapo-welfare-foundation',
    '마포복지재단',
    'foundation',
    'sigungu',
    '서울특별시 마포구',
    'https://www.mapowf.or.kr',
    'https://www.mapowf.or.kr/main/sub.html?boardID=www31',
    'html',
    720,
    70,
    'active',
    'medium',
    12,
    '{"site_ids":["mapo-welfare-foundation"],"adapter":"mapowf","maxPages":2,"boards":[{"name":"공지사항","url":"https://www.mapowf.or.kr/main/sub.html?boardID=www31","category":"복지"},{"name":"채용공고","url":"https://www.mapowf.or.kr/main/sub.html?page=5&boardID=www31&bCate=","category":"채용"}]}'::jsonb,
    '마포복지재단 기존 크롤러 설정 연동'
  ),
  (
    'youth-seoul',
    '청년몽땅정보통',
    'central_portal',
    'sido',
    '서울특별시',
    'https://youth.seoul.go.kr',
    'https://youth.seoul.go.kr/infoData/sprtInfo/list.do?key=2309130006',
    'html',
    360,
    88,
    'active',
    'medium',
    100,
    '{"site_ids":["youth-seoul"],"adapter":"youth-seoul","maxPages":2,"boards":[{"name":"청년지원정보","url":"https://youth.seoul.go.kr/infoData/sprtInfo/list.do?key=2309130006","category":"복지"}]}'::jsonb,
    '청년몽땅정보통 기존 크롤러 설정 연동'
  )
ON CONFLICT (source_slug) DO UPDATE SET
  name = EXCLUDED.name,
  source_type = EXCLUDED.source_type,
  region_scope = EXCLUDED.region_scope,
  region_name = EXCLUDED.region_name,
  homepage_url = EXCLUDED.homepage_url,
  list_url = EXCLUDED.list_url,
  collection_method = EXCLUDED.collection_method,
  collection_interval_minutes = EXCLUDED.collection_interval_minutes,
  priority = EXCLUDED.priority,
  status = CASE
    WHEN collection_sources.status IN ('paused', 'retired') THEN collection_sources.status
    ELSE EXCLUDED.status
  END,
  reliability = EXCLUDED.reliability,
  monthly_expected_posts = EXCLUDED.monthly_expected_posts,
  config_json = EXCLUDED.config_json,
  notes = EXCLUDED.notes,
  updated_at = now();

UPDATE collection_sources
SET
  status = 'retired',
  notes = 'mfac 수집기관으로 통합됨',
  updated_at = now()
WHERE source_slug = 'mapo-culture-foundation';
